//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714DBrandesex2h1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime FinishOrderDate { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Status StatusId { get; set; }
        public virtual Customer CustomerId { get; set; }
        public virtual ProcessType ProcessTypeId { get; set; }
    }
}
